install: gradle wrapper --gradle-version 4.2
before_script:
  - chmod +x gradlew
language: java
jdk:
  - openjdk8
notifications:
  slack:
    secure: CsbUFM+Vj+C/cxUoP14IMOETBWNSokl0d2kdPyP7cNvQdSuFm0tF1m2W/k1dAo1g2EU/woqWdbv7zbkASROV4E7Cui89VNnuLXMTJnC13Ve15rciCd0n0gOZG8zoOqzQujJTceQE7giFEKbIRjb3fpEAGAaUB5wq0IRcPySlW1s9w+JR6B4LZxdpsGSSVlmgpIcaj42AAfk6NBkZOY2BR2JINPe4rLKJod/nutHBHztWft0PSB0IP3KidbKEW4ET7OxoEfNB87/F2j2pNKk53+CZd1X7jftv6J0Or275grapRxVVxbs9R+1ma0LaHIGmR5Pd+5wzV2+xHdN+M4kmXcF7NU2Ma5Abp3IsA8+wZAPaXr/DsmEtuQweZe79CttDbX1veRwcw4LsKOArjh6paTn5h4qgLcG5UJcPK8fTFolBy4GEVHK95S+wCCqBB2Hmij5E+KY9skudZ84KZeOY637H0izi1ECj0Lc6kZfstwAiwxO5/RMG8u2GJiO2rVX7D54RrlFdULXnP1qxHWnxyevUHwn48RWqAmVewL6u3de/efjvdfGixqzqscEOqb7wiUiAaNCC1JuvZ5aqmvFjpPU1mpXwGlnaZfL5vhFOesPxN5QAlcFx/5VFEOjklz7LGszii9P9L0pMMRO3w0CqrZrd/3dvfGKa8+LV5h/sZe0=
